amazing_amazon/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#home"
  get "/home" => "welcome#home"
  get "/about" => "welcome#about"
  get "/contact_us" => "welcome#contact_us"
  get "/support_me" => "welcome#donate"
  get "/thank_you" => "welcome#thank_you"
  get "/new" => "bills#new"
  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/:provider/callback" => "callbacks#index"
  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post],
  )
  namespace :admin do
    resources :dashboard, only: [:index]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :tags, only: [:index, :show]
  resources :payment, only: [:create]
  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    resources :favourites, shallow: true, only: [:create, :destroy]
  end
  resources :news_articles
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
      resources :users, only: [:create] do
        get :current, on: :collection
        resources :reviews
      end
    end
    match "*unmatched_route", to: "application#not_found", via: :all
  end
end

def from_omniauth?
  uid.present? && provider.present?
end

amazing_amazon/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    alias_action(:create, :read, :update, :destroy, to: :crud)

    can(:crud, Product) do |product|
      user == product.user
    end

    can(:crud, Review) do |review|
      user == review.user
    end
  end
end

amazing_amazon/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

amazing_amazon/app/models/donation.rb
class Donation < ApplicationRecord
    belongs_to :user
  end
  

amazing_amazon/app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :product_id, uniqueness: { scope: :user_id, message: "has already been favourited "}
end

amazing_amazon/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review

  
  validates(
    :review_id,
    uniqueness:{
      scope: :user_id,
      message: "has already been liked"
    }
  )
end

amazing_amazon/app/models/news_article.rb
class NewsArticle < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :description, presence: true
    validate :published_at_after_created_at
    before_save :titlize_title
    belongs_to :user

    def published_at_after_created_at
        if published_at && created_at && (published_at < created_at)
            errors.add(:published_at, "must be after created_at")
        end
    end

    def titlize_title
        self.title = self.title.titlecase
    end

    def set_publish_time
        self.published_at = Time.now
    end
end

amazing_amazon/app/models/product.rb
class Product < ApplicationRecord
  validates(:title,
            presence: { message: "Title must be provided" },
            :uniqueness => { :case_sensitive => false })
  validates :price, numericality: { greater_than: 0 }
  validates :description, presence: { message: "Title must be provided" }, length: { minimum: 10 }
  before_validation :set_default_price, :capitalize_title
  DEFAULT_PRICE = 1
  scope :search, ->(query) { where("title ILIKE ? OR  description ILIKE ?", "%#{query}%", "%#{query}%") }
  validates_exclusion_of :title, in: %w( apple microsoft sony ), message: "please use a different title"
  belongs_to :user
  has_many :reviews, -> { order("updated_at DESC") }, dependent: :destroy

  has_many :favourites, dependent: :destroy
  has_many :favouriters, through: :favourites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def tag_names
    self.tags.map(&:name).join(", ")
  end

  def tag_names=(rhs)
    self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
      Tag.find_or_initialize_by(name: tag_name)
    end
  end

  private

  def capitalize_title
    self.title.capitalize!
  end

  def set_default_price
    self.price ||= DEFAULT_PRICE
  end
end

amazing_amazon/app/models/review.rb
class Review < ApplicationRecord
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  belongs_to :product
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  def vote_total
    votes.up.count - votes.down.count
  end
end

amazing_amazon/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :products, through: :taggings
  validates :name, presence: true, uniqueness: true
end

amazing_amazon/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :product

  validates(:tag_id, uniqueness: { scope: :product_id })
end

amazing_amazon/app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
  scope(:search, ->(search_term) { where("first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%") })
  has_many :votes, dependent: :destroy
  has_many :voted_reviews, through: :votes, source: :review
  has_many :likes, dependent: :destroy
  has_many :liked_reviews, through: :likes, source: :review

  has_many :favourites
  has_many :favourited_products, through: :favourites, source: :product
  has_many :donations, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}".strip.titleize
  end

  def from_omniauth?
    uid.present? && provider.present?
  end

  def self.create_from_oauth(oauth_data)
    name = oauth_data["info"]["name"]&.split || oauth_data["info"]["nickname"]
    self.create(
      first_name: name[0],
      last_name: name[1] || "",
      uid: oauth_data["uid"],
      provider: oauth_data["provider"],
      oauth_raw_data: oauth_data,
      password: SecureRandom.hex(32),
    )
  end

  def self.find_by_oauth(oauth_data)
    self.find_by(
      uid: oauth_data["uid"],
      provider: oauth_data["provider"],
    )
  end
end

amazing_amazon/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :user_id, uniqueness: {
              scope: :review_id,
              message: "has already been voted on",
            }

  validates :is_up, inclusion: {
            in: [true, false],
          }

  def self.up
    where(is_up: true)
  end

  def self.down
    where(is_up: false)
  end
end

amazing_amazon/app/helpers/auth_helper.rb
module AuthHelper
end

amazing_amazon/app/helpers/bills_helper.rb
module BillsHelper
end

amazing_amazon/app/helpers/dashboard_helper.rb
module DashboardHelper
end

amazing_amazon/app/helpers/reviews_helper.rb
MAX_RATING = 5

module ReviewsHelper
  def display_stars(review)
    full_stars = review.rating
    empty_stars = MAX_RATING - full_stars
    "#{("★" * full_stars)}#{"☆" * empty_stars}"
  end
end

amazing_amazon/app/helpers/sessions_helper.rb
module SessionsHelper
end

amazing_amazon/app/helpers/tags_helper.rb
module TagsHelper
end

amazing_amazon/app/helpers/users_helper.rb
module UsersHelper
end

amazing_amazon/app/helpers/votes_helper.rb
module VotesHelper
end

amazing_amazon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazing Amazon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 <%= stylesheet_pack_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <meta name="stripe-pk" content="<%= Rails.application.secrets.stripe_publishable_key %>">
  </head>

  <body>
    <div class="container">
    
<%= render "shared/navbar" %>

<%= render "shared/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

amazing_amazon/app/views/shared/_flash_messages.html.erb
<div >
  <% flash.each do |type, message| %>
    <div <%= type %>>
      <%= message %>
    </div>
  <% end %>
</div>

amazing_amazon/app/views/shared/_navbar.html.erb
<nav class='navbar navbar-light bg-light mb-5'>

<%= link_to "Home", home_path %> 
<%= link_to "Products", products_path %> 
<%= link_to "Tags", tags_path %> 
<%= link_to "New Product", new_product_path %> 
<%= link_to "About", about_path %> 
<%= link_to "Contact Us", contact_us_path %> 
    <% if user_signed_in? %>
      <%= link_to "Support us!", support_me_path %> 
      <span class='text-muted mr-3'>Hello, <%= current_user.full_name %></span>
      <%= button_to "Log Out", session_path, method: :delete, class: "btn btn-danger" %>
      <% if current_user.admin? %>
        <%= link_to "Dashboard", admin_dashboard_index_path, class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path, class: "btn btn-success" %>
<%= link_to "Sign in with Twitter", sign_in_with_twitter_path, class: "btn btn-success" %>
<%= link_to "Sign Up", new_user_path, class: "btn btn-success" %>

    <% end %>
  </nav>
  