amazing_amazon/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#home"
  get "/home" => "welcome#home"
  get "/about" => "welcome#about"
  get "/contact_us" => "welcome#contact_us"
  get "/support_me" => "welcome#donate"
  get "/thank_you" => "welcome#thank_you"
  get "/new" => "bills#new"
  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/:provider/callback" => "callbacks#index"
  match(
    "/delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post],
  )
  namespace :admin do
    resources :dashboard, only: [:index]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :tags, only: [:index, :show]
  resources :payment, only: [:create]
  resources :products do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
      resources :votes, only: [:create, :update, :destroy]
    end
    resources :favourites, shallow: true, only: [:create, :destroy]
  end
  resources :news_articles
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
      resources :users, only: [:create] do
        get :current, on: :collection
        resources :reviews
      end
    end
    match "*unmatched_route", to: "application#not_found", via: :all
  end
end

def from_omniauth?
  uid.present? && provider.present?
end

amazing_amazon/app/models/product.rb
class Product < ApplicationRecord
  validates(:title,
            presence: { message: "Title must be provided" },
            :uniqueness => { :case_sensitive => false })
  validates :price, numericality: { greater_than: 0 }
  validates :description, presence: { message: "Title must be provided" }, length: { minimum: 10 }
  before_validation :set_default_price, :capitalize_title
  DEFAULT_PRICE = 1
  scope :search, ->(query) { where("title ILIKE ? OR  description ILIKE ?", "%#{query}%", "%#{query}%") }
  validates_exclusion_of :title, in: %w( apple microsoft sony ), message: "please use a different title"
  belongs_to :user
  has_many :reviews, -> { order("updated_at DESC") }, dependent: :destroy

  has_many :favourites, dependent: :destroy
  has_many :favouriters, through: :favourites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def tag_names
    self.tags.map(&:name).join(", ")
  end

  def tag_names=(rhs)
    self.tags = rhs.strip.split(/\s*,\s*/).map do |tag_name|
      Tag.find_or_initialize_by(name: tag_name)
    end
  end

  private

  def capitalize_title
    self.title.capitalize!
  end

  def set_default_price
    self.price ||= DEFAULT_PRICE
  end
end

amazing_amazon/app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
  before_action :find_product, only: [:show, :destroy, :update]
  before_action :authenticate_user!, except: [:index, :show]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  rescue_from ActiveRecord::RecordInvalid, with: :record_invalid

  def index
    products = Product.order(created_at: :desc)
    render(json: products)
  end

  def show
    if @product
      render json: @product
    else
      render(json: { status: 404 }, status: 404)
    end
  end

  def create
    @product = Product.new product_params
    @product.user = current_user
    if @product.save
      render json: { id: @product.id }
    else
      render(
        json: { errors: @product.errors.messages },
        status: 422,
      )
    end
  end

  def update
    if @product.update product_params
      render json: { id: @product.id }
    else
      render(
        json: { errors: @product.errors },
        status: 422,
      )
    end
  end

  def destroy
    if @product.destroy
      render(json: { status: 200 }, status: 200)
    else render(json: { status: 500 })     end
  end

  protected

  def record_invalid(error)
    invalid_record = error.record
    errors = invalid_record.errors.map do |errorObject|
      {
        type: error.class.to_s,
        record_type: invalid_record.class.to_s,
        field: errorObject.attribute,
        message: errorObject.options[:message],
      }
    end
    render(
      json: { status: 422, errors: errors },
      status: 422,
    )
  end

  def record_not_found(error)
    render(
      status: 404,
      json: {
        errors: [
          {
            type: error.class.to_s,
            message: error.message,
          },
        ],
      },
    )
  end

  private

  def find_product
    @product ||= Product.find params[:id]
  end

  def product_params
    p params
    params.permit(:title, :description, :price)
  end
end

amazing_amazon/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, except: [:create, :index]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @products = Product.order(created_at: :DESC)
  end

  def new
  end

  def create
    @product = Product.new product_params
    @product.user = @current_user

    if @product.save
      ProductMailer.delay(run_at: 5.minutes.from_now).notify_product_owner(@product)

      redirect_to product_path @product
    else
      render :new
    end
  end

  def show
    @reviews = @product.reviews
    @review = Review.new
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def edit
  end

  def update
    if @product.update product_params
      redirect_to product_path @product
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :tag_names)
  end

  def authorize_user!
    unless can? :crud, @product
      flash[:danger] = "Access Denied"
      redirect_to root_path
    end
  end

  def load_product
    if params[:id].present?
      @product = Product.find(params[:id])
    else
      @product = Product.new
    end
  end
end

amazing_amazon/app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field(:title, class: "form-control", placeholder: "Product Name") %>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area(:description, class: "form-control", cols: 50, rows: 5, placeholder: "Provide Description") %>
  </div>
  <div class='form-group'>
    <%= f.label :price %>
    <%= f.number_field(:price, class: "form-control", min: 0, placeholder: "Enter Price", step: :any) %>
  </div>
     <div class='form-group'>
    <%= f.label :tag_names %>
    <%= f.text_field :tag_names %>
  </div>
    <%= f.submit %>
<% end %>

<script>
  $(function(){
    $('#product_tag_names').selectize({
      delimeter: ',',
      persist: false,
      labelField: 'name',
      valueField: 'name',
      searchField: 'name',
      options: <%= Tag.select(:name).to_json(except: [:id]).html_safe %>,
        create: function(input) {
        return {
            name: input 
        }
      }
    });
  });
</script> 

amazing_amazon/app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= render 'form'  %> 

amazing_amazon/app/views/products/index.html.erb
      <% @products.each do |product| %>
        <%= link_to product do %>
          <ul>
            <p><span><%= product.id %></span> <%= product.title %> <%= product.description %></p>
            
            <small>price <%= number_to_currency product.price %></small>
          </ul>
        <% end %>
      <% end %>

amazing_amazon/app/views/products/new.html.erb
<%= render "form" %>

amazing_amazon/app/views/products/show.html.erb
<div class='shadow-sm p-3 mb-5 bg-white rounded overflow-wrap'>
  <div class='clearfix'>
    <h1 class='float-left'>
      <span class='badge badge-pill badge-info'>
        <%= @product.id %>
      </span>
      <%= @product.title %>
    </h1>
    <h1 class='float-right text-center'>
        <span class='badge badge-pill badge-success'><%= number_to_currency @product.price %></span>
    </h1>
    
  </div>
  <small class='text-muted'>
    sold by <em><%= @product.user.full_name %></em>
  <small>
  <hr/>
  <p class='shadow-none p-3 rounded'><%= @product.description %></p>
  <p>Tags:</p>
  <% unless @product.tags.empty? %>
    <div>
      <% @product.tags.each do |tag| %>
        <%= link_to(
              tag.name,
              tag, class: "badge badge-pill badge-primary",
            ) %>
      <% end %>
    </div>
  <% end %>
  <div>
    <%= link_to(
          "Delete",
          product_path(@product),
          method: :delete,
          class: "btn btn-danger",
          data: { confirm: "are you sure?" },
        ) %>
    <%= link_to "Edit", edit_product_path(@product), class: "btn btn-info" %>
  </div>
</div> 
<p class='text-muted'>Leave a Review :D</p>
<div class='shadow-sm p-3 mb-5 bg-white rounded'>
  <%= form_with model: [@product, @review], local: true do |f| %>
    <div class='form-group'>
      <%= f.label :rating %>
      <%= f.select(:rating, options_for_select(1..5), class: "form-control") %>
    </div>
    <div class='form-group'>
      <%= f.label :body %>
      <%= f.text_area(:body, class: "form-control", placeholder: "Your thoughts here") %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

<h2> Here's what people are saying: </h2>

<% @product.reviews.each do |review| %>
  <div class='shadow-sm p-3 mb-1 bg-white rounded'>   
  <% # display_stars is a custom helper method to display stars located in /app/helpers/reviews_helper.rb %>
  <% # all methods defined in any helper file are available in all views :D. We can place complex logic in these helpers to avoid bloating our model. (business logic inside of controller should be kept to a minimum) %>
    <h4>
      <%= display_stars(review) %>
      <p class='font-weight-lighter d-inline-block'>by <%= review.user.full_name %></p>
               <%= button_to("Delete", product_review_path(@product.id, review.id), method: :delete, class: "btn btn-danger float-right",
                                                                                    data: { confirm: "Are you sure?" }) %>

    </h4>
    <p class='review-body text-muted'><%= review.body %></p>
    
  <% vote = review.votes.find_by(user: current_user) %>
      <span class="vote-widget">
        <% if vote.nil? %>
          <%= button_to "vote up", product_review_votes_path(review_id: review.id, product_id: review.product.id, is_up: true), method: :post %>
          <%= review.vote_total %> votes
          <%= button_to "vote down", product_review_votes_path(review_id: review.id, product_id: review.product.id, is_up: false), method: :post %>
        <% elsif vote.is_up? %>
          <%= button_to "vote up", vote_path(vote), method: :delete, class: "active" %>
          <%= review.vote_total %>
          <%= button_to "vote down", vote_path(vote, is_up: false), method: :patch %>
        <% else %>
          <%= button_to "vote up", vote_path(vote, is_up: true), method: :patch %>
          <%= review.vote_total %>
          <%= button_to "vote down", vote_path(vote), method: :delete %>
        <% end %>
      </span>

    <p>
      <% if user_signed_in? && can?(:like, review) %>
          <% like = current_user.likes.find_by_review_id(review) %>
          <% if like %>
            <%= link_to "Unlike", like_path(like), method: :delete %>
          <% else %>
            <%= link_to "Like", review_likes_path(review), method: :post %>
          <% end %>
      <% end %>
     <%= review.likes.count %> likes
    </p>
  </div>
<% end %>